<a href="https://colab.research.google.com/github/jeff-ai-ml/genai/blob/main/nlp_glove_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
! pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 70.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 102.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 16.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requ

In [1]:
import gensim.downloader as api

# Download and load the pre-trained GloVe model
model = api.load("glove-wiki-gigaword-100")  # You can choose different dimensions like 50, 100, 200, 300

# Example usage: get the embedding for a word
word = 'example'
embedding = model[word]

print(f"Embedding for '{word}':\n{embedding}")
print("Dimension:", len(embedding))
print("Type:", type(embedding))
print("Shape:", embedding.shape)


[==================================================] 100.0% 128.1/128.1MB downloaded
Embedding for 'example':
[-0.12617    0.61724    0.22581    0.39868    0.16111    0.1523
 -0.14715   -0.29447   -0.27348   -0.13753   -0.20898   -0.73436
  0.14144    0.15048    0.09179    0.018613   0.22539    0.15979
 -0.16935    0.42716    0.042284  -0.3477    -0.11413    0.12222
 -0.025027  -0.20805   -0.067264  -0.2956    -0.30807   -0.32903
  0.19059    0.77141   -0.19332   -0.31069    0.26745    0.32231
  0.2065     0.10497    0.49425   -0.38322   -0.12802   -0.069906
 -0.14828    0.085369  -0.18141    0.14688    0.60968   -0.21131
 -0.29148   -0.52773    0.59508    0.017369   0.15342    0.81925
 -0.20643   -2.0378    -0.11884   -0.16826    1.5288     0.15756
 -0.4994     0.39305    0.12672   -0.10968    1.3671    -0.21006
  0.15684    0.0063801  0.43836   -0.18765   -0.29088    0.18619
  0.085402   0.13985    0.40794   -0.14811    0.26702   -0.19142
 -0.6189     0.0091217  0.34971   -0.24079   

In [2]:
model.most_similar('usa')

[('canada', 0.6544384956359863),
 ('america', 0.645224392414093),
 ('u.s.a.', 0.6184033751487732),
 ('united', 0.6017189621925354),
 ('states', 0.5970699191093445),
 ('australia', 0.5838716626167297),
 ('world', 0.5590084195137024),
 ('2010', 0.5580702424049377),
 ('2012', 0.5504006743431091),
 ('davis', 0.5464468002319336)]

In [3]:
model['king']

array([-0.32307 , -0.87616 ,  0.21977 ,  0.25268 ,  0.22976 ,  0.7388  ,
       -0.37954 , -0.35307 , -0.84369 , -1.1113  , -0.30266 ,  0.33178 ,
       -0.25113 ,  0.30448 , -0.077491, -0.89815 ,  0.092496, -1.1407  ,
       -0.58324 ,  0.66869 , -0.23122 , -0.95855 ,  0.28262 , -0.078848,
        0.75315 ,  0.26584 ,  0.3422  , -0.33949 ,  0.95608 ,  0.065641,
        0.45747 ,  0.39835 ,  0.57965 ,  0.39267 , -0.21851 ,  0.58795 ,
       -0.55999 ,  0.63368 , -0.043983, -0.68731 , -0.37841 ,  0.38026 ,
        0.61641 , -0.88269 , -0.12346 , -0.37928 , -0.38318 ,  0.23868 ,
        0.6685  , -0.43321 , -0.11065 ,  0.081723,  1.1569  ,  0.78958 ,
       -0.21223 , -2.3211  , -0.67806 ,  0.44561 ,  0.65707 ,  0.1045  ,
        0.46217 ,  0.19912 ,  0.25802 ,  0.057194,  0.53443 , -0.43133 ,
       -0.34311 ,  0.59789 , -0.58417 ,  0.068995,  0.23944 , -0.85181 ,
        0.30379 , -0.34177 , -0.25746 , -0.031101, -0.16285 ,  0.45169 ,
       -0.91627 ,  0.64521 ,  0.73281 , -0.22752 , 

In [6]:
model['president']

array([-0.064549, -0.13812 ,  0.50017 ,  0.41434 ,  0.45832 , -0.048331,
       -0.21651 ,  0.34987 , -0.83235 , -0.62282 , -0.40099 , -0.31978 ,
        0.42928 , -0.026035, -0.16171 , -0.32513 ,  0.77604 , -0.39852 ,
       -0.67013 , -0.55876 , -0.39863 , -0.28143 ,  0.68614 ,  0.29229 ,
       -0.7146  ,  0.36995 , -0.45309 , -0.23193 ,  0.76916 , -0.031589,
        1.0603  ,  1.5446  , -0.13272 ,  0.33701 , -0.97561 ,  0.73617 ,
        0.60841 ,  0.558   , -0.39274 ,  0.1121  , -1.0474  , -0.03692 ,
        0.99908 , -0.044925, -0.41186 ,  0.19605 ,  0.093281, -0.59623 ,
       -0.60765 , -0.4742  , -0.30162 , -0.70128 , -0.20055 ,  0.99519 ,
        0.20088 , -2.5636  , -0.14627 ,  0.77824 ,  1.4913  ,  0.29724 ,
       -0.12084 , -0.060082,  0.079881, -0.38348 ,  0.41371 , -0.41284 ,
        0.61702 ,  1.1316  , -0.047434,  0.2848  ,  0.57694 , -0.45501 ,
       -0.76359 , -1.1659  ,  0.068946, -0.22498 ,  0.18691 ,  0.64142 ,
       -1.7505  , -0.091248,  0.85848 , -0.52203 , 

In [7]:
model['cake']

array([-0.94318 ,  0.59859 , -0.29723 , -0.18531 , -0.15003 ,  0.59964 ,
        0.86469 , -0.043638,  0.045402,  0.20723 ,  0.47813 ,  0.10392 ,
        0.18468 ,  0.67267 , -0.10693 ,  0.19472 ,  0.50381 , -0.20807 ,
       -0.029778, -0.57507 , -0.76517 ,  0.14342 , -0.041807, -0.36493 ,
        0.12316 ,  1.2181  , -0.065194, -0.20684 , -0.24247 , -1.0874  ,
       -0.31184 ,  0.60132 ,  0.72613 , -0.50184 ,  0.1892  ,  0.90248 ,
        0.048367,  0.14214 ,  0.23768 , -1.3184  , -0.082652, -0.76125 ,
        0.17832 , -0.46196 ,  0.13675 , -0.34033 , -1.1891  ,  0.021234,
        0.42358 ,  0.069305, -0.36826 , -0.39163 ,  0.1022  ,  1.0032  ,
       -1.1135  , -1.2909  ,  0.085113,  0.68631 ,  0.50096 ,  0.13337 ,
        0.25976 ,  0.92707 , -0.3682  , -0.4451  , -0.048682, -0.81138 ,
        0.51595 , -0.10593 , -0.12701 , -1.4975  , -0.41769 ,  0.41447 ,
        0.2363  ,  0.69452 ,  0.29314 ,  0.858   ,  0.31042 , -1.0194  ,
        0.90039 ,  0.92778 , -0.18078 , -0.3683  , 

In [8]:
model['bread']

array([-0.66146  ,  0.94335  , -0.72214  ,  0.17403  , -0.42524  ,
        0.36303  ,  1.0135   , -0.14802  ,  0.25817  , -0.20326  ,
       -0.64338  ,  0.16632  ,  0.61518  ,  1.397    , -0.094506 ,
        0.0041843, -0.18976  , -0.55421  , -0.39371  , -0.22501  ,
       -0.34643  ,  0.32076  ,  0.34395  , -0.7034   ,  0.23932  ,
        0.69951  , -0.16461  , -0.31819  , -0.34034  , -0.44906  ,
       -0.069667 ,  0.35348  ,  0.17498  , -0.95057  , -0.2209   ,
        1.0647   ,  0.23231  ,  0.32569  ,  0.47662  , -1.1206   ,
        0.28168  , -0.75172  , -0.54654  , -0.66337  ,  0.34804  ,
       -0.69058  , -0.77092  , -0.40167  , -0.069351 , -0.049238 ,
       -0.39351  ,  0.16735  , -0.14512  ,  1.0083   , -1.0608   ,
       -0.87314  , -0.29339  ,  0.68278  ,  0.61634  , -0.088844 ,
        0.88094  ,  0.099809 , -0.27161  , -0.58026  ,  0.50364  ,
       -0.93814  ,  0.67576  , -0.43124  , -0.10517  , -1.2404   ,
       -0.74353  ,  0.28637  ,  0.29012  ,  0.89377  ,  0.6740

In [11]:
model['eagle']

array([ 0.14804  , -0.73517  ,  0.18489  , -0.1354   ,  0.44248  ,
       -0.21856  ,  0.13677  , -0.41135  , -1.0976   , -0.61095  ,
        0.12922  ,  0.30442  ,  0.13611  ,  0.30299  ,  0.21108  ,
        0.014528 ,  0.60151  , -0.06086  , -0.049744 , -0.063286 ,
       -0.040335 ,  0.52373  , -1.2209   ,  0.53016  ,  0.93073  ,
        0.72648  , -0.45498  , -0.10123  , -0.27131  , -0.4825   ,
       -0.3315   ,  0.32011  ,  0.40652  ,  0.032205 ,  0.60969  ,
        0.10925  , -0.89431  ,  0.52856  ,  1.1142   ,  0.46922  ,
       -0.47274  ,  0.52841  , -0.49492  ,  0.77231  ,  0.13459  ,
        0.24898  ,  0.31614  ,  0.25661  , -0.66305  , -0.12503  ,
       -1.3364   ,  0.17884  , -0.32433  ,  0.56577  , -0.25321  ,
       -1.5523   ,  0.093222 ,  0.021419 ,  1.7271   ,  0.24759  ,
        0.44665  ,  0.71193  ,  0.46687  ,  0.96065  , -0.33141  ,
       -0.73373  , -0.31425  ,  0.07283  , -0.51399  ,  0.30981  ,
       -0.28211  , -0.23631  , -0.027368 ,  0.049798 ,  0.1858

In [12]:
model['kite']

array([-0.44415  ,  0.33178  , -0.39526  , -1.0643   ,  0.47886  ,
       -0.13532  ,  0.36438  , -0.20594  , -1.0238   , -0.29116  ,
       -0.5793   , -0.17532  ,  0.45521  ,  0.011077 , -0.11604  ,
        0.13484  , -0.70744  ,  0.32154  ,  0.48667  , -0.0086517,
       -0.081493 ,  0.52442  ,  0.58375  , -0.3252   ,  1.1649   ,
        0.78541  , -0.56358  , -0.15583  ,  0.25293  , -0.94752  ,
       -0.78586  ,  0.33027  ,  0.14607  ,  0.38629  ,  0.63705  ,
        0.16138  , -0.5367   ,  1.2902   ,  0.47352  , -0.2135   ,
       -1.1746   ,  0.33676  ,  0.06116  ,  0.56423  , -0.075322 ,
       -0.072501 ,  0.044608 , -0.39044  ,  0.14793  , -0.11562  ,
       -0.81937  , -0.012677 ,  0.17114  ,  0.050764 ,  0.31334  ,
       -0.6734   ,  0.5076   ,  0.92459  ,  0.55925  , -0.017132 ,
       -0.043266 ,  0.14368  ,  0.38599  ,  0.89214  , -0.46143  ,
        0.3817   ,  0.38855  ,  0.4456   , -0.17059  ,  0.24055  ,
       -0.86057  , -0.58088  ,  0.57459  ,  0.47492  , -0.1507

In [15]:
model.most_similar('usa')

[('canada', 0.6544384956359863),
 ('america', 0.645224392414093),
 ('u.s.a.', 0.6184033751487732),
 ('united', 0.6017189621925354),
 ('states', 0.5970699191093445),
 ('australia', 0.5838716626167297),
 ('world', 0.5590084195137024),
 ('2010', 0.5580702424049377),
 ('2012', 0.5504006743431091),
 ('davis', 0.5464468002319336)]

In [16]:
model.most_similar('cricket')

[('rugby', 0.7827098369598389),
 ('twenty20', 0.7362942099571228),
 ('england', 0.7173773646354675),
 ('indies', 0.715782105922699),
 ('cricketers', 0.7132172584533691),
 ('football', 0.6659637093544006),
 ('zealand', 0.6606222987174988),
 ('matches', 0.6509107351303101),
 ('bowling', 0.6504763960838318),
 ('wc2003-wis', 0.642265260219574)]

In [17]:
model.most_similar(negative='cricket')

[('kjellberg', 0.5707957148551941),
 ('stanciu', 0.5363406538963318),
 ('korot', 0.5251068472862244),
 ('ihle', 0.5189671516418457),
 ('meiling', 0.5106919407844543),
 ('malevich', 0.5092998147010803),
 ('68.23', 0.5047351717948914),
 ('morawetz', 0.5020094513893127),
 ('kissi', 0.5018949508666992),
 ('jean-antoine', 0.5003271102905273)]

In [23]:
result = model.most_similar(positive=['woman', 'king'] , negative=['man'])

print(f"{result[0]}")

('queen', 0.7698540687561035)
